include: package:lints/recommended.yaml

linter:
  rules:
    - always_declare_return_types
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures
    - unsafe_html
    - use_full_hex_values_for_flutter_colors
