name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    container:
      image: dart:stable

    steps:
      - uses: actions/checkout@v2

      - name: Print Dart SDK version
        run: dart --version

      - name: Install dependencies
        run: dart pub get

      - name: Run regression tests
        run: dart test

  coverage:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1

      - name: Print Flutter SDK version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Collect coverage
        run: flutter test --coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          file: coverage/lcov.info
          token: ${{secrets.CODECOV_TOKEN}}
